version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    env_file:
      - .env
