# Use the official Node.js 20 Alpine image as the base image
FROM node:20-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies 
RUN npm i

COPY . .

CMD ["npm", "run", "start:dev"]
