# Use an official Node.js runtime as a base image
FROM node:20-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code to the working directory
COPY . .

# Expose the port that your application will run on
EXPOSE $PORT

# Command to run your application
CMD ["npm", "run", "dev"]
